name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-python@v5
      with:
         python-version: '3.10'
         cache: 'pip'
         cache-dependency-path: ${{ github.action_path }}/requirements.txt
         


    - name: Debug Action Path
      run: |
        echo "GitHub Action Path: ${{ github.action_path }}"
        echo "Looking for .nvmrc at: ${{ github.action_path }}/requirements.txt"
        ls -l ${{ github.action_path }}
      shell: bash  # Specify the shell to use (bash in this case)
