
name: Test Python Cache Composite
description: Composite action to test pip caching for a non-root dependency file

runs:
  using: "composite"
  steps:
    - name: Print action path
      run: echo "github.action_path = ${{ github.action_path }}"
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: ${{ github.action_path }}/requirements.txt
