name: Reproduce Cache and pip Index Issue

on:
  workflow_dispatch:

jobs:
  setup-python:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [macos-latest, self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug runner environment
        run: |
          echo "Runner: ${{ runner.os }} / ${{ matrix.runner }}"
          echo "Python3_ROOT_DIR: $Python3_ROOT_DIR"
          echo "Toolcache path:"
          find /Users/runner/hostedtoolcache || true
          find /home/azureuser/actions-runner/_work/_tool || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Print Python paths
        run: |
          which python
          python --version
          echo "Python3_ROOT_DIR: $Python3_ROOT_DIR"

      - name: Restore Python cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: shared-python-cache-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            shared-python-cache-${{ runner.os }}-

      - name: Install pip with fallback index
        run: |
          python -m pip install --upgrade pip
        env:
          PIP_INDEX_URL: https://pypi.org/simple

      - name: Print pip version and exit
        run: pip --version
