name: PNPM Cache Workflow

on:
  workflow_call:
 

jobs:
  pnpm-cache-job:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.4
          cache: 'pnpm'

      - name: Get PNPM store path
        id: pnpm-store
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Restore PNPM cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store-${{ runner.os }}-18.20.4-v1

      - name: Install dependencies
        run: pnpm install --no-strict-peer-dependencies --ignore-script

      - name: Save PNPM cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store-${{ runner.os }}-18.20.4-v1
