name: tests 3.8

on:
  workflow_dispatch:

jobs:
  test:
    name: Test-macos
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        python:
        - "3.8"
        platform:
        - macos-12
        
    steps:  
      - name: Upgrade setuptools
        run: pip install --upgrade setuptools
      - name: Setup Python
        id: python-install
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true


 
  test2:
     
    strategy:
      # https://blog.jaraco.com/efficient-use-of-ci-resources/
      matrix:
        python:
        - "3.8"
        platform:
        - macos-latest
       
    runs-on: ${{ matrix.platform }}
    continue-on-error: ${{ matrix.python == '3.13' }}
    env:
      SETUPTOOLS_USE_DISTUTILS: ${{ matrix.distutils || 'local' }}
    timeout-minutes: 75
    steps:
      - uses: actions/checkout@v4
    
        
      - name: Setup Python
      
        id: python-install
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: false
      - name: Install dependencies
        run: python3 -m pip install -U build[virtualenv]
          
      
      - uses: actions/cache@v4
        id: cache
        with:
          path: setuptools/tests/config/downloads/*.cfg
          key: >-
            ${{ hashFiles('setuptools/tests/config/setupcfg_examples.txt') }}-
            ${{ hashFiles('setuptools/tests/config/downloads/*.py') }}
      - name: Populate download cache
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: setuptools/tests/config
        run: python -m downloads.preload setupcfg_examples.txt
      - name: Pre-build distributions for test
        shell: bash
        run: |
          rm -rf dist
          pipx run build
          echo "PRE_BUILT_SETUPTOOLS_SDIST=$(ls dist/*.tar.gz)" >> $GITHUB_ENV
          echo "PRE_BUILT_SETUPTOOLS_WHEEL=$(ls dist/*.whl)" >> $GITHUB_ENV
          rm -rf setuptools.egg-info  # Avoid interfering with the other tests
      - name: Install tox
        run: python -m pip install tox
      - name: Run
        run: tox
