name: Testing Pip install
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]       
    steps:
      - name: Checkout code
        uses: actions/checkout@v5 

      - name: Remove WindowsApps from PATH
        if: runner.os == 'Windows'
        run: |
          echo "PATH=${PATH//C:\\Users\\runneradmin\\AppData\\Local\\Microsoft\\WindowsApps;}" >> $env:GITHUB_ENV

      - name: Set up python
        uses: gowridurgad/setup-python@pip-install
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt 
          pip-install: -r requirements.txt
