name: Repro pip root warning

on: workflow_dispatch

jobs:
  python-root-warning:
    runs-on: self-hosted
    steps:
      - name: Setup Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
