name: Python Test

on: 

 workflow_dispatch:

jobs:
  setup-python:
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.x (invalid version)
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # This is the invalid version format.
        
    - name: Check Python version
      run: python --version  # This step should fail, as Python setup will not work with "3.x"


   
