name: Python Architecture Test

on:
  workflow_dispatch:

jobs:
  test-architecture:
    runs-on: macos-13
    strategy:
      matrix:
        python-version: [3.11, 3.12]  
        architecture: [universal2, arm64, x64]    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}  # Select architecture based on the matrix

    - name: Check Python architecture
      run: |
        echo "Python version: $(python --version)"
        echo "Python architecture: $(python -c 'import platform; print(platform.machine())')"
   
