name: Pypy Setup Test

on:
  workflow_dispatch:

jobs:
  test-python:
    runs-on: macos-latest
    
    steps:
      # Step 1: Check out the code repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up PyPy 2.7 on ARM64 architecture
      - name: Set up PyPy 2.7
        uses: actions/setup-python@v5
        with:
          python-version: "pypy-2.7"
          architecture: arm64  # Ensures ARM64 architecture is used

      # Step 3: Verify the PyPy setup (Optional)
      - name: Verify PyPy version
        run: |
          pypy --version
