name: Pypy Setup Test

on:
  workflow_dispatch:

jobs:
   test_python_location:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.11, pypy3.11]
    steps:
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: ls -al "$pythonLocation"
        shell: bash
      - run: |
          "$pythonLocation/python" -V
        shell: bash
