name: Test

on:
  workflow_dispatch:


jobs:
  test-v5:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.9'
         
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

  test-v4:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.9'
         
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
   
