name: python3.12-linux-test

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Set Python version
  test:
    name: Test-macos14
    runs-on: macos-14
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
          architecture: "x64"
          check-latest: true
      - name: print python version
        shell: bash
        run: python --version
