name: python3.12-linux-test

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: linux-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Set Python version
