name: test arm64 builds

on:
  workflow_dispatch:


jobs:
  test_job:
       runs-on: ubuntu-22.04         
       steps:
          - name: Check out repository
            uses: actions/checkout@v4
         
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
             python-version: '3.9'
             architecture: 'arm64'
             
