name: Test python install

on:
  workflow_dispatch:


jobs:
  test-v5:
    runs-on: self-hosted
  
         
    steps:
      - name: Ensure correct permissions for /Users/runner/hostedtoolcache
        run: |
          sudo chown -R runner-user:runner-group /Users/runner/hostedtoolcache

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.6
    

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
   
