name: fromJSON Template Parse Error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.produce.outputs.env_vars }}
    steps:
      - name: Conditionally skipped
        id: produce
        if: ${{ false }}
        run: echo "will never run"

  test-parse:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Attempt to parse with fallback
        run: |
          echo "${{ fromJson(needs.build.outputs.json || '{}').MAIN_BRANCH }}"
