name: Reproduce fromJson Empty Input Error

on:
  workflow_dispatch:
    inputs:
      trigger_error:
        type: boolean
        default: true
        description: "Set to true to skip the JSON-producing step and trigger the error"

jobs:
  generate-json:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.set-json.outputs.json }}
    steps:
      - name: Conditionally produce JSON
        id: set-json
        if: ${{ github.event.inputs.trigger_error == 'false' }}
        run: |
          echo "json={\"MAIN_BRANCH\": \"main\"}" >> $GITHUB_OUTPUT

  consume-json:
    needs: generate-json
    runs-on: ubuntu-latest
    steps:
      - name: Parse JSON output
        run: |
          echo "MAIN_BRANCH is: ${{ fromJson(needs.generate-json.outputs.json).MAIN_BRANCH }}"
