name: Composite Action Example
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: aparnajyothi-y/python-test@main
        
       

      - name: Print github.action_path
        run: |
          echo "The value of github.action_path is: ${{ github.action_path }}"
