name: Compare FQDN Performance and Workaround (macOS-14 vs macOS-15)

on:
  workflow_dispatch:

jobs:
  fqdn-test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python (3.12)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run FQDN timing test (setup-python)
        id: setup_test
        run: |
          echo "=== Testing setup-python installed Python on $RUNNER_OS ==="
          python - <<'EOF' | tee setup_output.txt
          import socket, time
          print("Testing socket.getfqdn() performance (setup-python)...")

          def measure(label, func):
              start = time.monotonic()
              func()
              print(f"{label}: {time.monotonic() - start:.2f}s")

          for host in ["127.0.0.1", "localhost", "localhost.", "localhost.localdomain"]:
              measure(host, lambda h=host: socket.getfqdn(h))
          EOF

      - name: Run FQDN timing test with workaround
        id: workaround_test
        run: |
          echo "=== Applying workaround: predefine HOSTNAME ==="
          export HOSTNAME=$(hostname)
          python - <<'EOF' | tee workaround_output.txt
          import socket, time, os
          print("Testing socket.getfqdn() performance with workaround...")
          print(f"HOSTNAME={os.environ.get('HOSTNAME')}")

          def measure(label, func):
              start = time.monotonic()
              func()
              print(f"{label}: {time.monotonic() - start:.2f}s")

          for host in ["127.0.0.1", "localhost", "localhost.", "localhost.localdomain"]:
              measure(host, lambda h=host: socket.getfqdn(h))
          EOF
