name: Test the tool-versions-regex

on:
 workflow_dispatch:
      
jobs:
  test-python:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macOS-13]
        
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python from tool-versions
        uses: aparnajyothi-y/setup-python@tool-versions-regex
        with:
          python-version-file: .tool-versions
