name: Test GIL-Free Error for <3.13

on:
  workflow_dispatch:

jobs:
  test-nogil:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup unsupported freethreaded Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.0'
          architecture: 'x64-freethreaded'
