name: Test Python Build

on:
  workflow_dispatch:


jobs:
  


  test_job:
       runs-on: windows-latest        
       steps:
          - name: Check out repository
            uses: actions/checkout@v4
         
          
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
             python-version: '3.13'
             

        
          
          

      
     


