name: test cache error message

on:
 workflow_dispatch:

jobs:
  testjobv5_2_0:
    name: test cache pip
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.11
          architecture: x64
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  testjobv_5_1_1:
     name: test cache pip for v5.1.1
     runs-on: ubuntu-latest
     
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v5.1.1
         with:
           python-version: 3.11
           architecture: x64
           cache: "pip"
       - name: Install dependencies
         run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  testjobv_4:
     name: test cache pip for v4
     runs-on: ubuntu-latest
     
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v5.1.1
         with:
           python-version: 3.11
           architecture: x64
           cache: "pip"

       - name: Install dependencies
         run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
            
      
