name: Diagnose Python Setup Differences

on:
  workflow_dispatch:

jobs:
  analyze-python-setup:
    runs-on: windows-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.16'

      - name: Locate Python install path
        id: find-python-path
        run: |
          $pyPath = (Get-Command python).Source
          Write-Host "Python executable path: $pyPath"
          $pythonRoot = Split-Path -Parent $pyPath
          echo "PYTHON_ROOT=$pythonRoot" >> $env:GITHUB_ENV

      - name: List all files under Python install path
        run: |
          Write-Host "Files under $env:PYTHON_ROOT"
          $files = Get-ChildItem -Path $env:PYTHON_ROOT -Recurse -Force | 
                   Select-Object FullName, Attributes, Length, LastWriteTime
          $files | Format-Table -AutoSize
          echo "File Count: $($files.Count)"
          
      - name: Dump file paths to artifact
        run: |
          $files = Get-ChildItem -Path $env:PYTHON_ROOT -Recurse -Force
          $fileList = $files | Select-Object FullName
          $fileList | Out-File -FilePath "$env:GITHUB_WORKSPACE\filelist.txt"

      - name: Upload file list artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-filelist-3.11.9
          path: filelist.txt
