name: Test Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add NVIDIA Package Repository
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:graphics-drivers/ppa
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
        echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /" | sudo tee /etc/apt/sources.list.d/cuda.list

    - name: Install CUDA and cuDNN
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cuda-11-4 \
          libcudnn8 \
          libcudnn8-dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.4'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Check TensorRT installation
      run: |
        python -c "import tensorrt; print('TensorRT version:', tensorrt.__version__)"
