name: Test Python Build

on:
  workflow_dispatch:


jobs:
  


  test_job:
       runs-on: ubuntu-latest          
       steps:
          - name: Check out repository
            uses: actions/checkout@v4
          - name: Install poetry
            run: pipx install poetry
          - name: add requirement.txt
            run: pip freeze > requirements. txt
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
             python-version: '3.10'
             cache: 'poetry' 
             cache-dependency-path: '**/poetry.lock'

          - run: poetry init
          - run: poetry install
          - run: poetry run pytest


      

          
          

      
     


