name: Reproduce Script Location Warning

on:
  push:
    branches:
      - main

jobs:
  install_and_check:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: aparnajyothi-y/setup-python@user-scripts-path
        with:
          python-version: '3.11'
          architecture: 'x86'
      
      - name: Install pyinstaller with --user flag
        run: |
          pip install pyinstaller --user
        

      - name: Verify installation
        run: |
          pyinstaller --version
          echo $Env:PATH
