name: Test PyPy Version Output

on:
  workflow_dispatch:

jobs:
  test-pypy:
    name: "Test PyPy ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy-3.10", "pypy-3.11"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Print resolved python-version output
        run: echo "Resolved: ${{ steps.python.outputs.python-version }}"

      - name: Restore venv cache
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ steps.python.outputs.python-version }}

      - name: Set up virtual environment if cache miss
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run test script
        run: |
          source .venv/bin/activate
          python --version
