name: Test Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CUDA and cuDNN
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cuda-11-4 \
          libcudnn8 \
          libcudnn8-dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.4'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Check TensorRT installation
      run: |
        python -c "import tensorrt; print('TensorRT version:', tensorrt.__version__)"
