# .github/workflows/fromjson-templatefail.yml
name: fromJSON Template Parse Error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.produce.outputs.env_vars }}
    steps:
      - name: Conditionally skipped
        id: produce
        if: ${{ false }}
        run: echo "::set-output name=env_vars::{\"MAIN_BRANCH\": \"main\"}"

  test-parse:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Attempt to parse empty input
        run: |
          echo "${{ fromJson(needs.build.outputs.json).MAIN_BRANCH }}"

