name: Python Setup Test

on:
  workflow_dispatch:

jobs:
  test-python:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenSSL
        run: choco install openssl

      - name: Set OpenSSL Environment Variables
        run: |
          setx OPENSSL_CONF "C:\Program Files\OpenSSL\bin\openssl.cfg"
          setx PATH "%PATH%;C:\Program Files\OpenSSL\bin"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy-3.9-nightly'

      - name: Show environment variables
        run: env

      - name: Python package install
        run: |
          pip install PyGObject

      - name: Log outputs
        run: |
          ls -la /opt/hostedtoolcache
          ls -la $(pwd)/_work/_tool
