name: Composite Action Cache Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python with cache
        # uses: actions/setup-python@v5
        uses: aparnajyothi-y/setup-python@Feature-request#476
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: requirements/required-test.txt

      - name: Print pip cache location
        run: pip cache dir
      - name: Install dependencies
        run: pip install -r requirements.txt
