name: Python Setup Test

on:
  workflow_dispatch:

jobs:
  test-python:
    runs-on: ${{ matrix.os }}
   
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          export RUNNER_TOOL_CACHE="$(pwd)/_work/_tool"
          export AGENT_TOOLSDIRECTORY="$(pwd)/_work/_tool"
          echo "RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE"
          echo "AGENT_TOOLSDIRECTORY=$AGENT_TOOLSDIRECTORY"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Show environment variables
        run: env

      - name: Verify Python paths
        run: |
          echo "Python include directory: $(python3 -c 'import sysconfig; print(sysconfig.get_path("include"))')"
          echo "Python library directory: $(python3 -c 'import sysconfig; print(sysconfig.get_path("platlib"))')"
          echo "Python site-packages directory: $(python3 -c 'import site; print(site.getsitepackages()[0])')"

      - name: Python package install
        run: |
          pip install PyGObject

      - name: Log outputs
        run: |
          ls -la /opt/hostedtoolcache
          ls -la $(pwd)/_work/_tool
