name: Reproduce Script Location Warning

on:
  push:
    branches:
      - main

jobs:
  install_and_check:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x86'
      
      
      - name: Install pywin32
        run: |
          python -m pip install --upgrade pip
          pip install pywin32
    
