name: Validate GraalPy Early Access Versions

on:
  workflow_dispatch:

jobs:
  test-graalpy-ea:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['graalpy23.1', 'graalpy24.1']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python with GraalPy EA version
        uses: timfel/setup-python@tim/graalpy-windows-ea
        with:
          python-version: ${{ matrix.python-version }}

      - name: Validate Python installation
        run: |
          python --version
          which python || where python
          pip --version || echo "pip not found"

      - name: Run sanity check
        run: |
          python -c "import sys; print('Running on:', sys.version)"
