name: Test Python Installation and Caching

on:
 workflow_dispatch:

jobs:
  setup-python-cache-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-latest]
        python-version: [3.11, 3.12]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies (test package)
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Example of installing a package
      
      - name: Cache Python dependencies
        uses: actions/cache@v4.0.0
        with:
          path: |
            ~/.cache/pip
            ${{ github.workspace }}/.tox
            ${{ runner.temp }}/pip-cache
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ matrix.python-version }}-pip-
            ${{ runner.os }}-python-${{ matrix.python-version }}-
            ${{ runner.os }}-python-
      
      - name: Verify cache contents
        run: |
          echo "Cache content verification:"
          ls -la ~/.cache/pip  # Verify if the cache has any contents

      - name: Verify Python version
        run: |
          python --version

      - name: List environment variables
        run: |
          echo "Python location: ${{ env.PYTHON_LOCATION }}"
