name: test cache error to warning

on:
 workflow_dispatch:

jobs:
  testjob_pip:
    name: test cache pip
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: aparnajyothi-y/setup-python@update-error-warning#436
      # - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
          cache: "pip"

      

  testjob_pipenv:
     name: test cache pipenv
     runs-on: ubuntu-latest
     
     steps:
       - uses: actions/checkout@v4
       - uses: aparnajyothi-y/setup-python@update-error-warning#436  
       # - uses: actions/setup-python@v5
         with:
           python-version: '3.12'
           architecture: x64
           cache: "pipenv"
      

  testjob_poetry:
     name: test cache poetry
     runs-on: ubuntu-latest
     
     steps:
       - uses: actions/checkout@v4
       # Install Poetry
       - name: Install Poetry
         run: pip install poetry
       - uses: aparnajyothi-y/setup-python@update-error-warning#436
       # - uses: actions/setup-python@v5
         with:
           python-version: '3.12'
           architecture: x64
           cache: "poetry"

       

      
            
      
