name: Validate Early Access Versions

on:
  workflow_dispatch:

jobs:
  test-ea:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.13.0b4', '3.13.0rc1', '3.14.0a1'] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python (EA Test)
      - uses: timfel/setup-python@tim/graalpy-windows-ea
        with:
          python-version: ${{ matrix.python-version }}

      - name: Validate Python Installation
        run: |
          python --version
          which python
          pip --version

      - name: Run Sanity Tests
        run: |
          python -c "import sys; print('Python OK:', sys.version)"
