name: Test

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: macOS 13.4.1
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.8'
          - '3.9'
        
         
          
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
          architecture: aarch64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
   

     

# vim:set et sts=2:
