name: Test PyPy Version Output

on:
  workflow_dispatch:

jobs:
   test-pypy:
    name: "Test PyPy ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy-3.10", "pypy-3.11"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        id: python
        # uses: actions/setup-python@v5.6.0
        uses: cdce8p/setup-python@pypy-version-output
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
      - run: echo "${{ steps.python.outputs.python-version }}"
      - name: Restore Python venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: venv
          key: >-
            ${{ runner.os }}-${{ runner.arch }}-${{ steps.python.outputs.python-version
            }}-${{ hashFiles('pyproject.toml', 'requirements.txt') }}

      - name: Create Python venv (skip pydantic if PyPy 3.11)
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip setuptools wheel

          if [[ "${{ matrix.python-version }}" == "pypy-3.11" ]]; then
            echo "Skipping pydantic for PyPy 3.11"
            grep -v 'pydantic' requirements.txt > filtered-req.txt
            pip install -r filtered-req.txt || true
          else
            pip install -r requirements.txt
          fi

          pip install .
