name: Test GraalPy Version Output

on:
  workflow_dispatch:

jobs:
  test-graalpy:
    name: "Test GraalPy ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["graalpy-3.10", "graalpy-3.11"] # Use available versions
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Show resolved version
        run: 'echo "Resolved Python version: ${{ steps.python.outputs.python-version }}"'


      - name: Check Python version
        run: python --version

      - name: Check Python implementation
        run: |
          python -c "import platform; print(platform.python_implementation())"

      - name: Restore Python venv
        id: cache-venv
        uses: actions/cache@v4.2.3
        with:
          path: venv
          key: >-
            ${{ runner.os }}-${{ runner.arch }}-${{ steps.python.outputs.python-version }}-${{ hashFiles('pyproject.toml', 'requirements.txt') }}

      - name: Create Python venv
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt || true
          pip install . || true
