name: Composite Action Example
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache-dependency-path: requirements/required.txt

       

      - name: Print github.action_path
        run: |
          echo "The value of github.action_path is: ${{ github.action_path }}"
