name: test cache pip

on:
 workflow_dispatch:

jobs:
  testjob:
    name: Compute results
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
