name: Test Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.4'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Check TensorRT installation
      run: |
        python -c "import tensorrt; print('TensorRT version:', tensorrt.__version__)"
