# .github/workflows/fromjson-templatefail.yml
name: fromJSON Template Parse Error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.produce.outputs.env_vars }}
    steps:
      - name: Conditionally skipped step
        id: produce
        if: ${{ false }}
        run: echo "This should not run"
        # intentionally doesn't set output if skipped

  consumer:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Handles skipped step safely
        run: echo "MAIN_BRANCH = ${{ fromJson(needs.build.outputs.json || '{}').MAIN_BRANCH }}"
