name: Test Python Build

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false         
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel

  test_client_job:
       runs-on: ubuntu-latest          
       steps:
          - name: Check out repository
            uses: actions/checkout@v4
          - name: Install poetry
            run: pipx install poetry
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
             python-version: '3.10'
             cache: 'poetry' 

          - run: poetry install --without dev 

  test_client_job1:
       runs-on: ubuntu-latest          
       steps:
          - name: Check out repository
            uses: actions/checkout@v4
          - name: Install poetry
            run: pipx install poetry
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
             python-version: '3.9'
             cache: 'poetry' 

          - run: poetry install
          - run: poetry run pytest

  test_client_job2:
       runs-on: ubuntu-latest  
       steps:
         - uses: actions/checkout@v4
         - name: Install poetry
           run: pipx install poetry
         - run : poetry init
         - name: Set up Python
           uses: actions/setup-python@v5
           with:
            python-version: '3.10'
            cache: 'poetry'
         - run: poetry install 
         - run: poetry run python .\main.py
        
      
      

          
          

      
     


