name: Python Setup Test

on:
  workflow_dispatch:

jobs:
  test-python:
    runs-on: self-hosted
    env:
      RUNNER_TOOL_CACHE: ${{ github.workspace }}/_work/_tool
      AGENT_TOOLSDIRECTORY: ${{ github.workspace }}/_work/_tool
   
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Show environment variables
        run: env

      - name: Verify Python paths
        run: |
          echo "Python include directory: $(python3 -c 'import sysconfig; print(sysconfig.get_path("include"))')"
          echo "Python library directory: $(python3 -c 'import sysconfig; print(sysconfig.get_path("platlib"))')"
          echo "Python site-packages directory: $(python3 -c 'import site; print(site.getsitepackages()[0])')"

      - name: Python package install
        run: |
          pip install PyGObject

      - name: Log outputs
        run: |
          ls -la /opt/hostedtoolcache
          ls -la $(pwd)/_work/_tool
