name: test cache
on:

  workflow_dispatch:
  
jobs:
  latest:
    name: latest
    runs-on: macos-latest
        
    steps:
    - name: Clone repo
      uses: actions/checkout@v4.1.1
    - name: Set up python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip wheel   
          
    - name: Cache dependencies
      uses: actions/cache@v4.0.0
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements/required.txt') }}-${{ hashFiles('requirements/datasets.txt') }}-${{ hashFiles('requirements/tests.txt') }}
     
   
  minimum:
    name: minimum
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone repo
      uses: actions/checkout@v4.1.1
    - name: Set up python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.10'
    - name: Cache dependencies
      uses: actions/cache@v4.0.0
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements/min-reqs.old') }}-${{ hashFiles('requirements/mins-cons.old') }}
   
