name: test cache error message

on:
 workflow_dispatch:

jobs:
  testjob:
    name: test cache pipenv
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64
          cache: "pip"

            
      
