name: tests setuptools

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      # https://blog.jaraco.com/efficient-use-of-ci-resources/
      matrix:
        python:
        - "3.8.10"
        - "3.12"
        platform:
        - macos-latest
       
    runs-on: ${{ matrix.platform }}
    continue-on-error: ${{ matrix.python == '3.13' }}
    env:
      SETUPTOOLS_USE_DISTUTILS: ${{ matrix.distutils || 'local' }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        id: python-install
        uses: aparnajyothi-y/setup-python@testensure
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
