name: test cache pip

on:
 workflow_dispatch:

jobs:
  testjob:
    name: Compute results
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: aparnajyothi-y/setup-python@v5
        with:
           python-version: '3.7.17'
           cache: 'poetry'
