name: Python Matrix Test

on:
  workflow_dispatch :

jobs:
  tests:
    name: "Test on Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "pypy-3.10", "pypy-3.11"]

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4.2.2

      - name: Set up Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
