name: Test setup-python on Node 20

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use PR branch of setup-python
        uses: salmanmkc/setup-python@node24
        with:
          python-version: 3.12

      - name: npm i
        run: npm install
      - name: Confirm Node version
        run: |
          echo "Node version:"
          node -v
          echo "npm version:"
          npm -v
