name: test cache key

on:
 workflow_dispatch:

jobs:
  testjob:
    name: test cache pipenv
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: aparnajyothi-y/setup-python@PR#896-test
        with:
           python-version: '3.7.17'
           cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install

  testjobpip:
    name: test cache-pip
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: aparnajyothi-y/setup-python@PR#896-test
        with:
           python-version: '3.10'
           cache: 'pip'
      - run: pip install -r requirements.txt

  testjobpoetry:
    name: test cache-poetry
    runs-on: macos-latest

    steps:
        - uses: actions/checkout@v4
        - uses: aparnajyothi-y/setup-python@PR#896-test
          with:
             python-version: '3.12'
             cache: 'poetry'
        - name: Install Poetry
          run: curl -sSL https://install.python-poetry.org | python3 -
        - name: Add Poetry to PATH
          run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        - name: Cache Poetry Dependencies
          uses: actions/cache@v3
          with:
            path: |
              ~/.cache/pypoetry
              ~/.cache/pip
            key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
            restore-keys: |
              ${{ runner.os }}-poetry-
        - run: poetry install
        - run: poetry run pytest

      

  
     
