name: Checkout and Setup of Workflow
on: 
 workflow_dispatch:
 
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.0-beta.1'
          architecture : 'x64-freethreaded'
      - name: Check Python version
        run: python --version
