name: Path update for >=3.10
on:
  workflow_dispatch:

jobs:
  install_and_check:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: aparnajyothi-y/setup-python@update-install-path
        # uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'
          architecture: 'x64'
          freethreaded: true
      
      - name: Install pyinstaller with --user flag
        run: |
          pip install pyinstaller --user
        

      - name: Verify installation
        run: |
          pyinstaller --version
          echo $Env:PATH
