name: user post setup Tests withb v5
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          
        python-version:
          - 3.8
          - 3.9
          - "3.10"
    steps:
     
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup msbuild on Windows
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.1
      - name: Set up Visual Studio shell
        if: matrix.os == 'windows-latest'
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
      - name: Check out source repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install networkx
          pip3 install --pre torch -f "${{ steps.pytorch_channel.outputs.value }}"
          pip3 install cmake ninja
          echo "/home/runner/.local/bin" >> $GITHUB_PATH
      - name: Build TorchData
        run: |
          pip3 install .
        env:
          BUILD_S3: 1
      - name: Install test requirements
        run: pip3 install -r test/requirements.txt
      - name: Test documentation examples
        run: |
          cd ./docs
          pip3 install -r requirements.txt
          make doctest
          cd ..
      - name: Run StatefulDataLoader tests with pytest
        if: ${{ ! contains(github.event.pull_request.labels.*.name, 'ciflow/slow') }}
        run: pytest --durations=0 --no-header -v test/stateful_dataloader
