name: user post setup Tests
on:
 workflow_dispatch:

jobs:
  test:
  
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - 3.8
          - 3.9
          - "3.10"
    steps:
     
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup msbuild on Windows
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.1
      - name: Set up Visual Studio shell
        if: matrix.os == 'windows-latest'
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
      - name: Check out source repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install networkx
         
      - name: Build TorchData
        run: |
          pip3 install .
        env:
          BUILD_S3: 1
      - name: Install test requirements
        run: pip3 install -r test/requirements.txt
      - name: Test documentation examples
        run: |
          cd ./docs
          pip3 install -r requirements.txt
          make doctest
          cd ..
     
