name: User Post Setup Tests with v3
on:
  workflow_dispatch:



jobs:
  version_or_release:
    name: 'Version and open PR (or) release private packages'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: 'Production - Private Packages'
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v4
    

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'  # Use 'pnpm' to enable pnpm caching

  

      - name: Check for pnpm-lock.yaml
        run: |
          if [ ! -f "pnpm-lock.yaml" ]; then
            echo "pnpm-lock.yaml file is missing in the repository."
            exit 1
          else
            echo "pnpm-lock.yaml file found."
          fi

      

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Debug Cache Directory
        run: |
          echo "Contents of PNPM Cache Directory:"
          ls -la $PNPM_CACHE_FOLDER  # Verify the cache directory contents

      - name: List Node Modules
        run: |
          echo "Contents of Node Modules Directory:"
          ls -la node_modules  # Check the node_modules structure
