name: CI Workflow with pnpm path

on:
  workflow_dispatch :
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js with pnpm
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Specify the Node.js version you need
        cache: 'pnpm'

    - name: Set pnpm store path
      run: pnpm config set store-dir ${{ github.workspace }}/.pnpm-store

    - name: Install dependencies with pnpm
      run: pnpm install
