name: user post setup Tests with v3
on:
  workflow_dispatch:

env:
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  version_or_release:
    name: 'Version and open PR (or) release private packages'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: 'Production - Private Packages'
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm store config
        run: |
          pnpm config set store-dir $PNPM_CACHE_FOLDER
          echo "Configured pnpm store directory: $PNPM_CACHE_FOLDER"

      - name: Check PNPM Cache Path
        run: echo "Cache path: $PNPM_CACHE_FOLDER"

      - name: List pnpm cache contents
        run: ls -la $PNPM_CACHE_FOLDER || echo "Cache directory does not exist"

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: $PNPM_CACHE_FOLDER
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: List node_modules
        run: ls -la node_modules || echo "node_modules directory does not exist"
