name: python-x64 on arm64

on:
  workflow_dispatch:


jobs:
    
  
  test:
    name: Test-macos
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10','3.11','3.12']
       
        
        
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.1'
          architecture: 'x64'
        
          
