name: python-x64 on arm64

on:
  workflow_dispatch:


jobs:
    
  
  test:
    name: Test-macos
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
        python-version: ['3.9', '3.10']
      
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x86

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
        
          
