name: python-x64 on arm64

on:
  workflow_dispatch:


jobs:
    
  
  test:
    name: Test-macos
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12-arm64]
        python-version: ['3.7', '3.8', '3.9', '3.10']

       
        
        
    steps:
      - uses: aparnajyothi-y/setup-python@testmacoslatest
        with:
          python-version: ${{ matrix.python-version }} 
          architecture: 'x64'
        
          
