name: python-macos14-test

on:
  workflow_dispatch:


jobs:
    
  
  test:
    name: Test-macos
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.7, 3.8, 3.9, 3.10]
        
        
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
        
          
